### ISSUE TITLE
EPIC 2.1 TVB-NEST co-simulation (Lionel v2)

### ISSUE THREAD

**Issue by w-klijn** [multiscale-cosim/EBRAINS-cosim#102]
name: TVB-NEST co-simulation (Lionel v2)
about: Showcase 2, second, advanced version by Lionel

 Aspect       | Detail
--------------|--------------
Summary       | 
Task Area     | 
Assignee      |
Information   | 
Prerequisites | 
Dependencies  | 

## Tasks

- [ ] Investigate current version, synchronize with Lionel
- [ ] Highlight differences
   - [ ] science related parts
   - [ ] design parts
   - [ ] programming and technical parts
- [ ] Include in MVP iteration (v2) design
- [ ] (if necessary) adapt InterscaleHUB design

**Comment by sontheimer** [comment]
Added first tasks.
Summary, description and dependencies missing.
