### ISSUE TITLE
EPIC 2.2 ARBOR, insite pipeline

### ISSUE THREAD

**Issue by w-klijn** [multiscale-cosim/EBRAINS-cosim#103]
Kim

**Comment by sontheimer** [comment]
Added first tasks.
Summary, description and dependencies missing.

**Comment by sontheimer** [comment]
tasks to consider and link to other cards:

- [ ] collect requirements and description
    - [ ] ARBOR integration, usecase, i/o
    - [ ] Insite pipeline usecase, i/o
- [ ] define interface to cosim framework
