### ISSUE TITLE
MPI's Socket Communication Integration Test on 'local' system for the TVB-NEST/launcher application

### ISSUE THREAD

**Issue by ringleschavez** [multiscale-cosim/EBRAINS-cosim#111]
Aspect       | Detail
--------------|--------------
Summary       |  The integration-test of the MPI's Socket communication approach for the TVB-NEST/launcher code.
Task Area     | Research, Development
Assignee      | @ringleschavez 
Information   | Exclusively Point-to-Point approach must be tested, i.e. one-to-one
Prerequisites | 
Dependencies  | #74 #82 

## Summary
Having worked on the TVB-NEST-demo on "local" VM, there were found different issues related to the MPI's "socket-style"
communication approach.

In order to become aware of the scope and limitations about of the mentioned approach, the Integration-Test
on TVB-NEST/launcher will allow to have a set of test showing how the MPI's Socket-Style communication approach
could be used in the Co-Simulation Framework.
## Tasks
- [x] Designing and developing the Integration-Test XML Configuration Files
- [x] Developing the Socket-Server python scripts for the Integration-Test used by the TVB-NEST/launcher application
- [x] Implementing the Socket-Client python scripts for the Integration-Test used by the TVB-NEST/launcher application
- [x] Making up the Integration-Test and performing preliminary test on 'local' system (VM).
- [x] Fixing found issues
- [x] Tidying up the configuration files and python scripts.
- [x] Performing the pull-request.

## Requirements

- A 'local' (VM) with a MPI library and MPI4PY able to compile and run in order to perform preliminary tests of the MPI's Socket-Style communication approach.

## Acceptance criteria

- Integration-Test for the TVB-NEST/launcher application demonstrating the usage of the MPI's Socket-Style communication functional to the Co-Simulation Framework.

## Remarks
- It would be worth to perform tests by using MPICH and OpenMPI.
- Similarly, testing the blocking and non-blocking calls could be a different Integration-Test.
- Finally, both communication method could be tested as well, namely, "memory buffer communication" (`Comm.Send`, `Comm.Recv`) and "Python objects communication" (`Comm.send`, `Comm.recv`).
- 
## References:
[1] https://mpi4py.readthedocs.io/en/stable/overview.html#collective-communications
[2] https://mpi4py.readthedocs.io/en/stable/tutorial.html#point-to-point-communication
[3] https://www.hlrs.de/about-us/media-publications/teaching-and-training-material/MPI-course-material/
[4] https://pages.tacc.utexas.edu/~eijkhout/pcse/html/mpi-proc.html#Socket-stylecommunications
[5] https://web.corral.tacc.utexas.edu/CompEdu/pdf/pcse/

**Comment by ringleschavez** [comment]
Former list of task until 2022-02-27:
Creating a Socket-Server program
Creating a Socket-Client program
Testing MPI Socket-Server on receive mode
Testing MPI Socket-Server on send mode
Testing MPI Socket-Server on mixed mode (receive/send)
Testing MPI Socket-Server on 1-to-n approach
Integration-Test Configuration Files
Python scripts for the Integration-Test used by the TVB-NEST/launcher application

**Comment by ringleschavez** [comment]
Examples how `MPI.Comm.Probe` could be used for received messages checking:

https://github.com/mpi4py/mpi4py/blob/master/test/test_p2p_buf.py
https://github.com/mpi4py/mpi4py/blob/master/demo/mpi-ref-v1/ex-2.29.py

**Comment by ringleschavez** [comment]
https://github.com/multiscale-cosim/TVB-NEST/pull/21/commits/bac545e9952028c3dde7472381446fb63764a4b6
