### ISSUE TITLE
Refactor code Lionel to extract endpoint

### ISSUE THREAD

**Issue by w-klijn** [multiscale-cosim/EBRAINS-cosim#14]
Aspect       | Detail
--------------|--------------
Summary       | Factor out POC Lionel to extract the endpoint type functionality
Task Area     | Refactoring
Assignee      | Wouter Klijn
Information   | 
Prerequisites | POC can be looked at by Wouter, #9, #10 
Dependencies  | 

## Summary
As the first example of a Cosim following the decomposition suggest for EBRAINS multiscale workflow. The requirements of the TVB-NEST cosim should be supported. To clarify what are the needs for this functionality, the code should be refactored in such a way that there is a clear separation of concerns:
MPI functionality is an implementation detail and should be hidden from the simulator 
The protocol might be hidden from the simulator?

suggested dependency:
[ data exchange class]
- Data lock
- Data buffer
- public members to get and set
   * implement the protocol
- has a connection endpoint

[connection endpoint]
- Abstracts away the connection type
- Has a X endpoint 

[MPI endpoint]
-Contains all MPI related info

## Tasks
- [x] Refactor a single data stream until separation of concern is clear
- [x] Refactor out MPI related info
    - [x] Move all MPI connection and communicator creation to a separate location
    - [x] Move all communications, Threads and MPI, to a separate location
    - [x] Start refactoring the translation code to MPI.
    - [ ] NEST to TVB direction **(IN PROGRESS)**
    - [ ] TVB to NEST direction
- [x] Refactor out data exchange class
- [ ] Update the rest of the code based on example
    - [ ] Create FatEndpoint (class/file)
    - [ ] Create NEST-TVB sender/receiver with FatEndpoint
    - [ ] Encapsulate the components 
- [ ] Common code should be put in separate project (FatEndpoint) see...
- [ ] Review

## Requirements
Code should be publicly online for reviews a [repo (forked)](https://github.com/sontheimer/TVB-NEST/tree/mpi-refactor/nest_elephant_tvb/translation).

## Acceptance criteria

- The test used as green-light after each change/commit: `test_translation_nest_to_tvb.sh`
- Pull request reviewed.

**Comment by sontheimer** [comment]
Kim: start working on FatEndpoint - [connection endpoint] - [MPI endpoint]

**Comment by sontheimer** [comment]
Updated the issue, added current task an marked 'in progress'.

**Comment by w-klijn** [comment]
Continue work in #57 or a new card
