### ISSUE TITLE
Epic: EEG signals from co-simulation with NEST and LFPy

### ISSUE THREAD

**Issue by torbjone** [multiscale-cosim/EBRAINS-cosim#22]
Aspect       | Detail
--------------|--------------
Summary       | Calculate EEG signals from NEST simulation through the hybrid scheme
Task Area     | Co-simulation
Assignee      | Torbjørn V Ness
Information   | torbjorn.ness@nmbu.no

## Summary
For comparison with experiments, NEST simulations should ideally be able to simulate measurable signals, like Local Field Potentials (LFPs) and Electroencephalography (EEG). However, point-neurons can not in themselves produce such signals, and additional tricks are needed. The hybrid scheme has previously been used to allow LFP calculation from NEST simulations through the Hybrid Scheme, but the extracranially measured EEG signals are more complicated, since they require a head model.

## Tasks

- [x] Implement method to calculate current dipole moments from arbitrary simulated biophysically detailed neural activity (SGA2)
- [x] Combine current dipole moments with simple four sphere head models (SGA2) 
- [x] Combine current dipole moment with complex head models
- [x] Make results available through Github repository
- [x] Make approach available through scientific publication

**Comment by torbjone** [comment]
Paper demonstrating this is finally published. 
https://www.sciencedirect.com/science/article/pii/S1053811920309526?dgcid=rss_sd_all
