### ISSUE TITLE
Scientific use case: Neurophilosophers on co-simulation; accomodation and architecture

### ISSUE THREAD

**Issue by DeLaVlag** [multiscale-cosim/EBRAINS-cosim#23]
Aspect       | Detail
--------------|--------------
Summary       | Build multiscale models to simulate the neural correlates of conscious action and volition, based on experimental protocols and presentation timing similar to that used in the human neural-imaging experiments, which will be driven by human-like stimuli.
Task Area     | 
Assignee      |  @DeLaVlag Michiel van der Vlag (Julich Supercomputer Centre), D. Silverstein (Neurophilosophy of free will)
Information   |  m.van.der.vlag@fz-juelich.de, David Silverstein [davidsi@solvable.systems]
Prerequisites | 
Dependencies  | Design of co-simulation environment incuding TVB - NEST - Arbor

## Summary (from working document D. Silverstein, 2020)

The four-year neurophilosphy of free will project consists of experimental neuroscience,
philosophical investigations and computational experiments. We aim for the computational models
to be integrated with the other findings, suggesting testable hypotheses and allowing experimental
results to inform the models. To do this, we seek to build multiscale models to simulate the neural
correlates of conscious action and volition, based on experimental protocols and presentation timing
similar to that used in the human neural-imaging experiments. The intention is that the
computational model itself will be driven with human-like stimuli, similar to using presentation
tools such as PsychoPy (Peirce et al. 2019), but in simulation time.

Consider a general reaction time task with a human subject, who is presented with a visual Rapid
Serial Visual Presentation (RSVP) stream of images every 100 ms and is asked to press a button
when recognizing an expected target. This task can be decomposed into segments such as conscious
awareness of the target, perceptual decision making (does the image match the target?), motor
decisions (should the button be pressed?) and a motor action when pressing the button. At the
macroscale, performing such tasks can generate ERPs such as the P300, Readiness Potential (RP),
Lateralized Readiness Potential (LRP), Central-Parietal Positivity (CPP), Event-related De-
Synchronization (ERD/ERS) and others. A reaction time experiment might be considered a
structural scaffolding for simulations, which can be elaborated to approach target experiments. For
example, some free-will and decision making experiments may use a similar paradigm with
elaborations of the stimulus, choice presentation or motor segments (e.g. Aim 2.5).

Our goal in computational modeling over the next few months is to model the first segment of
reaction time, when conscious awareness and possible recognition of a target may occur. This seeks
to validate an approach using The Virtual Brain (TVB) (Sanz-Leon et al. 2013; Woodman et al.
2014; thevirtualbrain.org) with brain area nodes at multiple scales within the same simulation.
Some nodes will utilize neural masses (i.e. Jansen-Rit, reduced Wong-Wang) (Jansen & Rit 1995;
Wong & Wang 2006) and other nodes along relevant signaling pathways will use more detailed
neural attractor nodes that will store a set of attractor memories as neural assemblies.

Two different scales of attractor network nodes will be explored. One node type will utilize a
oscillatory attractor model (OAM) across a population of abstract non-spiking oscillatory neurons.
The other node type will utilize a spiking attractor model (SAM) across a population of integrate-
and-fire, Izhikevich or Made-To-Order neurons within a neocortical patch. It is possible that spiking
neurons are needed for realistic timing of signal transduction across brain pathways for tasks such
as reaction time. Activity from the attractor networks can potentiate neural mass nodes and vice
versa. The output of the model is to include EEG/MEG-like data generated with TVB, which can be
used to identify ERPs such as the P300. It may also be possible to apply drift-diffusion methods to
the model output as well.

## Tasks

- [ ] Define attractor memories as a subset of nodes in the local population with directionality, weights and latencies between them.
- [ ] Implement TVB proxy node which produces activity from reading a timeseries file. (use- case 1, near term)
- [ ] Standalone SAM simulation - In the near term, extend existing V1->V2 parallel Neuron attractor code to include additional areas along the signaling pathway. Run the simulation stand-alone and save summarized node activity to timeseries files. Import those files into proxy SAM nodes in TVB to run simulations and generate possible ERPs. Utilizes MPI. (use-case 1, near term)
- [ ] TVB-OAM – Use TVB-multiscale and TVB-Nest as a template to link TVB to OAM with a Python-Octave bridge. Modify Matlab code to encapsulate individual nodes and load/store attractor memories and attractor-attractor projections according to a common specification. Utilizes a multicore processor but not MPI (use-case 2, near term)
- [ ] Psychopy simulation driver - Uses experimental design files (.psyexp and trial files) created with Builder to map stimulation and monitoring events to simulation correlates in the computational model, based on simulation time. On stimuli correlates, a specific attractor memory is stimulated with a given strength and duration. If the stimulation produces an action, map that to a subject feedback event such as a button press. Sample experiments can include choice reaction time, attentional blink, backward masking, stroop. A goal is to compare the ERP simulation output trials with human experimental trials. (longer term)
- [ ] Possibly implement a skeleton version to integrate existing attractor code in Neuron with TVB, for multithreaded simulations without MPI. (use-case 3)
- [ ] Integrated SAM simulation - Longer term, port SAM code to PyNest/Nest. TVB and the simulator run in sync and transfer data bidirectionally, as specified by TVB-multiscale and/or TVB-elephant-nest. Smaller simulations are likely possible with the simulator
running as a multi-threaded process, but larger simulations are likely dependent on a multiscale MPI implementation for the attractor nodes. (use-case 4, longer term)
