### ISSUE TITLE
Epic: LFP from NEST version of the Allen model of mouse V1

### ISSUE THREAD

**Issue by torbjone** [multiscale-cosim/EBRAINS-cosim#24]
Aspect       | Detail
--------------|--------------
Summary       | Calculate LFPs from NEST version of the Allen model of mouse V1 through the Kernel Method
Task Area     |  Co-simulation of LFPs/EEGs from point-neuron and firing rate models
Assignee      | Torbjørn V. Ness
Information   |  torbjorn.ness@nmbu.no

## Summary
The large-scale model of mouse V1, developed by the Allen Institute for Brain Science, comes in two implementation, one with biophysically detailed cell models (NEURON simulator), and one with point neurons (NEST simulator). The biophysically detailed version can be used to calculate LFP signals, but is very computationally heavy, while the point neuron version is much computationally lighter, but can not in itself predict LFP signals.

We are working on applying the so-called kernel method to the biophysically detailed implementation to calculate LFP kernels, which are essentially mappings from firing rate to LFP signals for each cell population. This will allow calculation of LFP signals directly from the point neuron version of the model, and can also be used for firing rate models.

## Tasks

- [ ] In collaboration with the Allen Institute, make modified version of Allen Institute's BMTK software for calculation of kernels (https://github.com/AllenInstitute/bmtk/tree/feature/spont_syn_activation)
- [ ] Test approach in simplified version of Allen model
- [ ] Apply to full scale version of biophysically detailed model
- [ ] Quantify difference between LFP calculated by standard approach and LFP reconstructed by kernel method
- [ ] Publish results

**Comment by w-klijn** [comment]
Which group in the Allen institute is this? The Simlab has a different project starting up on parameter exploration. If this is the same group it would be good to know this.

**Comment by torbjone** [comment]
I don't know what the group is called, but our "lead contact" for most of our work with the Allen Institute is Anton Arkhipov. The modified version of BMKT was done directly by Kael Dai, which is one of the main developers of their BMTK software, but from here on, we expect to be able to do most of the work ourselves.
