### ISSUE TITLE
Software installation on Deep-est

### ISSUE THREAD

**Issue by sontheimer** [multiscale-cosim/EBRAINS-cosim#26]
Aspect       | Detail
--------------|--------------
Summary       | Installation of the related software and existing POC on the Deep-est cluster. 
Task Area     | Installation 
Assignee      | Kim Sontheimer
Information   | 
Prerequisites | 
Dependencies  | 

## Summary
Installation of relevant software on the Deep-est cluster. Integration and usage of the software and the tools will be in separate issues.

## Tasks

- [ ] Names are authors and contacts. Discussion and confirmation needed.

- [ ] ELK stack for monitoring (Kim)
- [ ] Translators
    - [ ] Nest-Elephant coupling, includes Nest and Elephant (Kim)
    - [x] Nest-TVB, includes TVB (Lionel, Wouter)
- [ ] Nest Desktop (Sebastian)
- [ ] Insite (Benni, Simon)

**Comment by w-klijn** [comment]
Should be moved to ice-box as we are waiting on a new project on deepest.
