### ISSUE TITLE
Move NEST Desktop from Angular to Vue.js

### ISSUE THREAD

**Issue by jens-br** [multiscale-cosim/EBRAINS-cosim#29]
Aspect       | Detail
--------------|--------------
Summary       | This task covers the move of NEST Desktop from Angular to Vue.js.
Task Area     | Enhancement
Assignee      | @bweyers @babsey @jens-br 
Information   | @babsey 
Prerequisites | 
Dependencies  | 

## Summary
The current version of NEST Desktop is based on Angular. Since Vue.js would offer a much more lightweight solution which should be significantly easier to maintain, NEST Desktop will move to Vue.js.
The performance should improve as well according to first tests.

## Tasks
- [ ] Investigation (requirements engineering)
   * draft: components/architecture, data structure definition
- [ ] Concrete architecture plan for Vue version
   * system architecture
   * data structure
   * interfaces (NEST Server, Insite/Elephant)
- [ ] Refactor existing version to simplify swap
- [ ] Swap out
- [ ] Testing
   * bug testing
   * acceptance testing
- [ ] Rework of the user documentation

**Comment by bweyers** [comment]
Just updated the current work status!
