### ISSUE TITLE
Co-simulation TVB-NEst for demonstation 

### ISSUE THREAD

**Issue by lionelkusch** [multiscale-cosim/EBRAINS-cosim#34]
Aspect       | Detail
--------------|--------------
Summary       | a week for creating a demonstrator
Task Area     | Functionality
Assignee      | @lionelkusch @w-klijn 
Information   | Preparation for a demonstration of the group of Neurophilosopher
Prerequisites | 
Dependencies  | 

## Tasks

- [x] Merge request 2 in master
- [x] Use json format  for parameter 
Change test_nest, parameter_manager and run_exploration for saving parameter
Change simulation_zerlaut and tvb_to_nest for reading parameters from a json file.
- [x] Check if the following tests pass :  test_input_nest_current.sh, test_input_nest_current_multi.sh,  test_input_nest_spike.sh, test_nest_save.sh, test_record_nest_spike.sh, test_record_nest_spike_multi.sh, test_nest_to_tvb.sh, test_tvb_to_nest.sh
- [x] Fix bugs of the test_co-sim.sh on deepest and if the other test pass
- [x]  Update the Read Me
- [x] Move file in better logic 
- [x] Put everything in the Public reporsitory
- [ ] refactor the translation files in the following way : 
[refact_translation.pdf](https://github.com/multiscale-cosim/EBRAINS-cosim/files/4986758/refact_translation.pdf)

## Acceptance criteria
One week

**Comment by lionelkusch** [comment]
The refactoring will be not done now
