### ISSUE TITLE
Automatizing the installation process of the EBRAINS-orchestrator components

### ISSUE THREAD

**Issue by ringleschavez** [multiscale-cosim/EBRAINS-cosim#36]
Aspect       | Detail
--------------|--------------
Summary       | Developing the cmake scripts for all the components that form the EBRAINS-orchestrator as a whole
Task Area     | Installation
Assignee      | Rolando Inglés r.ingles.chavez@gmail.com
Information   | 
Prerequisites | 
Dependencies  | 

## Summary
The EBRAINS-orchestrator will be deployed as component 
## Tasks
- [x] Task 1 - Defining the main CMakeLists.txt
- [x] Task 2 - Checking the multi-scale co-sim prerequisites
- [ ] Task 2 - developing the cmake script for each component of the EBRAINS-orchestrator
- [ ] ...

### Task 1- main cmake
 Aspect       | Detail
--------------|--------------
Aim | Defining the main CMakeLists.txt
Rationale |  Since the EBRAINS-orchestrator is an ensemble of several components, one  main CMakeLists.txt file should be placed on the top directory of the tree. By design, cmake tool goes trough the whole tree in order to execute the subsequent CMakeLists.txt files placed on the sub-directories.  By means of the this main CMakeLists.txt, some general checking will be defined.

### Task 2 - Checking the multi-scale co-sim prerequisites
 Aspect       | Detail
--------------|--------------
Aim | Checking the proper installation of the components required to execute the EBRAINS-orchestrator
Rationale | Since the EBRAINS-orchestrator is a component which will execute co-simulation jobs, the prerequisites components, libraries, simulators must be already installed in order to use it.

### Prerequisites Installation
The TVB and NEST simulators should have been already deployed on the system where the test will be run

### Cloning EBRAINS-orchestrator repository
`git clone -b <some_branch_name> https://github.com/multiscale-cosim/EBRAINS-orchestrator.git`

### Install the EBRAINS-orchestrator by means of cmake run on the top
`cmake <params>`

### Execute the integration test

**Comment by w-klijn** [comment]
Simulator introspection tool: 
https://github.com/VRGroupRWTH/insite/tree/develop You should use the develop branch for now as we did some larger changes. An official release with the changes included is planned for beginning of December as my last major action in the HBP. Everything is packaged inside docker containers. Documentation on how to get it running and an overview of our REST API can be found here: https://vrgrouprwth.github.io/insite/

We also have arbor support in development but any contributions are definitely welcome! Maybe it makes sense to fork the repository so that we can pull changes back to our repository?

Additional information:
Krüger, Marcel <Krueger@vr.rwth-aachen.de>
Oehrl, Simon <Oehrl@vr.rwth-aachen.de>
