### ISSUE TITLE
Centralized Log Manager

### ISSUE THREAD

**Issue by mfahdaz** [multiscale-cosim/EBRAINS-cosim#37]
Aspect       | Detail
--------------|--------------
Summary       |  Centralize the logging
Task Area     | 
Assignee      | Muhammad Fahad
Information   | 
Prerequisites | #40 
Dependencies  | 

## Summary

A centralized logging manager facilitates all Co-Sim modules to participate in logging by following a uniform format and to provide a critical introspection/visibility into the application with a minimal setup for deeper analysis and troubleshooting. It generates the context-rich logs, captures the exception tracebacks, and route the logs to appropriate destinations.

## Tasks

- [x] Centralized configuration settings for logging (e.g to customize the priority level, formats, destinations, etc.) 
- [ ] Refactor the existing logging to resolve the code duplication
- [ ] Incorporate the tracebacks and exception handling for generating a more context-rich logging information
- [ ] Add custom levels to generate more specialized data for monitoring
- [x] Format the logs and to centralize them so it can be parsed by a log management/monitoring platform for more effective troubleshooting and debugging

**Comment by w-klijn** [comment]
First version of logging manager has been implemented
