### ISSUE TITLE
Developing EBRAIN Co-Sim jobs/tasks launcher 

### ISSUE THREAD

**Issue by ringleschavez** [multiscale-cosim/EBRAINS-cosim#39]
Aspect       | Detail
--------------|--------------
Summary       | Developing a python module to start processes 
Task Area     | Development New Components
Assignee      | ringleschavez
Information   | r.ingles.chavez@gmail.com
Prerequisites | 
Dependencies  | Logging componet

## Summary
This issue refers to the developing of a module for launching/starting EBRAIN Co-Sim jobs/tasks based on an XML configuration file, the sequence how the jobs/tasks are started will be defined on the script where the launcher module is used. Thus, the launcher object will identify which jobs/tasks could be started based on an XML configuration file. 

## Tasks
- [ ] Create the skeleton of the launcher module
- [ ] Modify EBRAINS-Orchestrator CMakeFiles.txt in order to install on the proper location to be used by the test case scripts
- [ ] Import the module from existent test case scripts in order to check that the module is properly reachable.
- [ ] Implement the XML configuration file manager.
- [ ] Implement the launcher class method which will start the requested tasks/jobs by means of subprocess.Popen(...)
- [ ] Create a new test case script based on one of the existent one, which the new launcher module must be used.
- [ ] Add the appropriate methods in order to complete the functionally required to manage the started processes.
- [ ]  Implement the mechanism of cancellation (SIGINT).
- [ ] Add the logging message by using the EBRAINS Co-Sim logging module.
- [ ] Develop unit tests for the developed launcher module.

## Requirements
- The module should provide an abstract interface to start new processes oriented to brain co-simulation experiments.
- The processes will be launched based on the content of the XML configuration file provided during the creation of the launcher object.
- The launcher module consumer script will request which co-sim job must started by means of the name identification, which must be declared in the launcher XML configuration file and whose parameters must be defined as well.
- The processes IDs must be provided in order to manage them, e.g. interrupt, suspend, stop.
- Logging messages should be sent into the files defined on the launcher's XML configuration file

## Acceptance criteria
Running the brain co-simulation process based on the existent test_co-sim.sh script must behave in the same way that the a new script which uses the jobs launcher module.

**Comment by w-klijn** [comment]
Continue work in #62
