### ISSUE TITLE
Investigating Logging Manager Architecture Design

### ISSUE THREAD

**Issue by ringleschavez** [multiscale-cosim/EBRAINS-cosim#40]
Aspect       | Detail
--------------|--------------
Summary       | Design and implementation choices for the Logging Manager
Task Area     | Investigation
Assignee      | Avnii and ringleschavez
Information   | 
Prerequisites | 
Dependencies  | 

## Summary
Analysis of different choices for the Logging Manager design and implementation
- To provide a centralized configuration settings
- The format for different severity levels (such as DEBUG, INFO, WARNING, etc),
- The destination of logs
- A customized log level to handle the monitoring data

## Tasks
- [x] Analyzing the existing approach used in TVB-NEST co-sim use cases
- [x] Defining how the logger manager will be configured and what format will be used? (different choices for consideration includes XML, JSON, YAML, Python Dictionary, and etc.)
- [x] Looking over to the formats for different (verbosity) levels for different severity levels
- [x] Analyzing the different choices for emitting the logs (choices are one common file, distributed amongst designated places, and etc.)
- [ ] Defining a new customized log level (format, emitting destination, etc.) for handling the monitoring data
- [ ] Defining the monitoring points that are essential to assess the workflow health
- [ ] Analyzing how the logging will be used by different components?
- [ ] Defining how to Logging to a single file from multiple MPI processes?

## Requirements
- Reviewing the best practices for logging in Python
- Exploring the existing Python's standard libraries to parse and manipulate the configuration files in different format

**Comment by w-klijn** [comment]
First version of logging manager has been implemented
