### ISSUE TITLE
Refactor: MPI communication in translation modules

### ISSUE THREAD

**Issue by sontheimer** [multiscale-cosim/EBRAINS-cosim#43]
Aspect       | Detail
--------------|--------------
Summary       |  Refactor the translation modules to use MPI communication instead of multithreading 
Task Area     | Refactor, Implementation, 
Assignee      | @sontheimer 
Information   | 
Prerequisites | 
Dependencies  | 

## Summary
The current implementation uses MPI intercommunicators, sending and receiving as well as Multithreading for connection and communication. To prevent deadlocks and related issues, this refactoring will move to pure MPI communication.
This also enables scaling in the future. 

## Tasks

- [x]  Move all MPI connection and communicator creation to a separate location
- [x] Move all communications, Threads and MPI, to a separate location
- [x] Start refactoring the translation code to MPI.
    - [ ] NEST to TVB direction
    - [ ] TVB to NEST direction

## Acceptance criteria
 The test used as green-light after each change/commit: `test_translation_nest_to_tvb.sh`

**Comment by sontheimer** [comment]
Duplicate of #14.
Copied overlap and closed this issue.
