### ISSUE TITLE
Integrate the Insitu pipeline with NEST Desktop

### ISSUE THREAD

**Issue by jens-br** [multiscale-cosim/EBRAINS-cosim#44]
Aspect       | Detail
--------------|--------------
Summary       | Integrate the Insitu pipeline with NEST Desktop
Task Area     | Functionality
Assignee      | @babsey @bweyers @jens-br 
Information   | @babsey 
Prerequisites | 
Dependencies  | #29 ( #17 )

## Summary
The Insitu pipeline should be integrated with NEST Desktop.

## Tasks

- [ ] Organize and hold kickoff meeting
- [ ] Requirements engineering
- [ ] Adapt data structure
- [ ] Extend Insite initialization
- [ ] GUI adaptation of control
- [ ] Testing
