### ISSUE TITLE
Services: (Steering)

### ISSUE THREAD

**Issue by mfahdaz** [multiscale-cosim/EBRAINS-cosim#50]
Aspect       | Detail
--------------|--------------
Summary       | 
Task Area     | 
Assignee      |
Information   | 
Prerequisites | 
Dependencies  | #49 #55 

## Summary
Command and steering service routes the steering and commands from Orchestrator to Application Companions and the responses from application companions to Orchestrator.

Steering interactive applications: start stop resume kill
We need a single point where we can send these commands. 
POC could be a python application with a prompt.

Requirement for models: multiple simulate(time) steps. We can stop and start at these synchronosation steps.
This assures that all spikes are send and received.
Kill can be send at all times.

Other things related to this:
1. Synchronizing the step-size of the simulators (Model init phase) #52
2.  Establishing the connection, signaling protocol.  #48 

## Tasks
- [x] Create a diagram with the steering service in the center with all the different components which relate to it
- [x] Define the requirements: roles / functions
- [x] Rough class diagram and functions (arguments)

**Comment by mfahdaz** [comment]
estimated TBD by 10.08.2021

**Comment by mfahdaz** [comment]
Rough design diagram can be found [here](https://app.diagrams.net/#G14hwIMr_M7sFRqjNqeKP9lUmOhvJdZvdL). Later, it will be moved to design document located at [HBP Wiki drive](https://wiki.ebrains.eu/bin/view/Collabs/multi-simulator-interaction-and-co-simul/Drive).
