### ISSUE TITLE
Orchestrator

### ISSUE THREAD

**Issue by mfahdaz** [multiscale-cosim/EBRAINS-cosim#52]
Aspect       | Detail
--------------|--------------
Summary       | MVP Design of the Orchestration component in Co-Simulation
Task Area     | Design
Assignee      |
Information   | 
Prerequisites | #48 
Dependencies  | #49, #69, #67, #46

## Summary
The orchestrator is responsible for runtime coordination between different components in the cosimulation deployment. 
One important task will be the alignment of the minimal delays of the simulators connected: This information in the worst case is only available after the models have been instantiated.
Additionally this component would also be the controller of the starting / stopping and pausing behavior. 

## Tasks
- [x] Create a diagram with the orchestrator in the center with all the different components which relate to it
- [x] Define the requirements: roles / functions
- [x] State machine design to control simulation progress and states
- [x] Decide on speak versus hub intelligence.
- [x] Rough class diagram and functions (arguments)

## Requirements
The communication also in the single node deployment should use queues as this will make the multi node deployment in phase two a lot more easier

## Acceptance criteria
Tasks have been completed and documented in this issue and in the design document.

**Comment by w-klijn** [comment]
Potential source of additional information:  #6

**Comment by mfahdaz** [comment]
estimated TBD by 10.08.2021

**Comment by mfahdaz** [comment]
Rough design diagram can be found [here](https://app.diagrams.net/#G14hwIMr_M7sFRqjNqeKP9lUmOhvJdZvdL). Later, it will be moved to design document located at [HBP Wiki drive](https://wiki.ebrains.eu/bin/view/Collabs/multi-simulator-interaction-and-co-simul/Drive).
