### ISSUE TITLE
1.1 Transformer

### ISSUE THREAD

**Issue by mfahdaz** [multiscale-cosim/EBRAINS-cosim#53]
Aspect       | Detail
--------------|--------------
Summary       | MVP Design of the Transformer component in Co-Simulation
Task Area     | Design 
Assignee      |
Information   | 
Prerequisites | 
Dependencies  | Dependent on requirements of different simulator inputs and outputs 

## Summary
A minimal viable product design of the transformer component in Co-Simulation.
## Tasks

- [x] Update card: rename and description
- [x] Check interfaces to other MVP components

**old tasks:**
- [x] Define general tasks of a transformer
- [x] Define endpoints to the simulators 
- [x] Define parts that are specific to the usecase
- [x] Create diagrams

**Comment by sontheimer** [comment]
Transformer itself renamed to InterscaleHUB, details moved into new card
