### ISSUE TITLE
Launcher

### ISSUE THREAD

**Issue by mfahdaz** [multiscale-cosim/EBRAINS-cosim#54]
Aspect       | Detail
--------------|--------------
Summary       | Design of the Laucnhercomponent in Co-Simulation
Task Area     | Design
Assignee      |
Information   | 
Prerequisites | #48, #49, 
Dependencies  | #69, #67 #46

## Summary
The launcher is responsible to spawn processes in run time to achieve Co-Simulation experiments. 

## Tasks
- [x] Create a diagram with the launcher in the center with all the different components which relate to it
- [x] Define the requirements: roles / functions
- [x] Rough class diagram and functions (arguments)

## Requirements
No requirements

## Acceptance criteria
Set of consensual diagrams

**Comment by mfahdaz** [comment]
Rough design diagram can be found [here](https://app.diagrams.net/#G14hwIMr_M7sFRqjNqeKP9lUmOhvJdZvdL). Later, it will be moved to design document located at [HBP Wiki drive](https://wiki.ebrains.eu/bin/view/Collabs/multi-simulator-interaction-and-co-simul/Drive).

**Comment by ringleschavez** [comment]
Diagrams for the very first running version of the launcher:

![general_classes_view](https://user-images.githubusercontent.com/75490842/144834600-950362ba-958e-47e5-b710-498dfa720918.png)
![detailed_classes_view](https://user-images.githubusercontent.com/75490842/144834684-b63f4d1b-1973-40e9-b6c9-3d1cfcbab453.png)
