### ISSUE TITLE
Rich-endpoint  - minimal steering API

### ISSUE THREAD

**Issue by mfahdaz** [multiscale-cosim/EBRAINS-cosim#55]
Aspect       | Detail
--------------|--------------
Summary       | 
Task Area     | 
Assignee      |
Information   | 
Prerequisites | #50 
Dependencies  | #49 #69 #60 #48

## Summary
Command and steering service routes the steering and commands from Orchestrator to Application Companions and the responses from application companions to Orchestrator.

Requirement for models: multiple simulate(time) steps. We can stop and start at these synchronosation steps.
This assures that all spikes are send and received.
Kill can be send at all times.

Other things related to this:
1. Synchronizing the step-size of the simulators (Model init phase) #52
2.  Establishing the connection, signaling protocol.  #48 

## Tasks
- [x] Simple application exposing a prompt (1: Init 2: start 3: stop.)
- [x] Receive Command and Steering from Orchestrator
- [x] Broadcast Command and Steering to all Application Companions
- [x] Send step sizes to Orchestrator after receiving from Application Companions
- [x] Integration of Command and Steering service in RichEndpoint

**Comment by mfahdaz** [comment]
estimated TBD by 10.08.2021

**Comment by mfahdaz** [comment]
Closed with [PR](https://github.com/multiscale-cosim/EBRAINS-RichEndpoint/pull/1).
