### ISSUE TITLE
TVB - Elephant - NEST

### ISSUE THREAD

**Issue by sontheimer** [multiscale-cosim/EBRAINS-cosim#57]
Aspect       | Detail
--------------|--------------
Summary       | The TVB-NEST Co-Simulation using the Elephant framework as translation module 
Task Area     | Scientific use-case in Co-simulation
Assignee      |
Information   | 
Prerequisites | Descriptions from use-case owners
Dependencies  | 

## Tasks
Update on the current status of ELEPHANT integration needed.
- [ ] rename card
- [ ] update tasks

**Comment by w-klijn** [comment]
Data from old card regarding refactoring (#14)

## Summary
As the first example of a Cosim following the decomposition suggest for EBRAINS multiscale workflow. The requirements of the TVB-NEST cosim should be supported. To clarify what are the needs for this functionality, the code should be refactored in such a way that there is a clear separation of concerns:
MPI functionality is an implementation detail and should be hidden from the simulator 
The protocol might be hidden from the simulator?

suggested dependency:
[ data exchange class]
- Data lock
- Data buffer
- public members to get and set
   * implement the protocol
- has a connection endpoint

[connection endpoint]
- Abstracts away the connection type
- Has a X endpoint 

[MPI endpoint]
-Contains all MPI related info

## Tasks
- [x] Refactor a single data stream until separation of concern is clear
- [x] Refactor out MPI related info
    - [x] Move all MPI connection and communicator creation to a separate location
    - [x] Move all communications, Threads and MPI, to a separate location
    - [x] Start refactoring the translation code to MPI.
    - [ ] NEST to TVB direction **(IN PROGRESS)**
    - [ ] TVB to NEST direction
- [x] Refactor out data exchange class
- [ ] Update the rest of the code based on example
    - [ ] Create FatEndpoint (class/file)
    - [ ] Create NEST-TVB sender/receiver with FatEndpoint
    - [ ] Encapsulate the components 
- [ ] Common code should be put in separate project (FatEndpoint) see...
- [ ] Review


## Requirements
Code should be publicly online for reviews a [repo (forked)](https://github.com/sontheimer/TVB-NEST/tree/mpi-refactor/nest_elephant_tvb/translation).

## Acceptance criteria

- The test used as green-light after each change/commit: `test_translation_nest_to_tvb.sh`
- Pull request reviewed.

**Comment by sontheimer** [comment]
Original issue is moved to new issues/cards, together with the MVP related issues.

Update on the current status of ELEPHANT integration needed.
[ ] rename card
[ ] update tasks

**Comment by sontheimer** [comment]
This issue is split up and moved to three individual issues:
- TVB-NEST usecase and refactoring
- MVP InterscaleHUB (translator-transformer-InterscaleHUB)
- Elephant integration as external plugin, including parallel analysis
