### ISSUE TITLE
co-simulation orchestrator V2

### ISSUE THREAD

**Issue by w-klijn** [multiscale-cosim/EBRAINS-cosim#6]
Aspect       | Detail
--------------|--------------
Summary       | The orchestrator is responsible for runtime coordination of information exchange
Task Area     | functionality
Assignee      | 
Information   | 
Prerequisites | 
Dependencies  | 

## Summary
Multi-scale sees a lot of different components exchanging data at runtime. Additionally the different simulators need to synchronize time steps, exchange MPI configurations, register port for exchange of information. Not all this information is know at configuration time and thus needs to be exchanged at runtime.  To prevent a multitude of point to point communications a single access point (presumably using a message queue) will be available for each simulator to send and retrieve these types of information.
 
Additionally the orchestrator will provide basic status information of the different components deployed.

## Tasks
- [ ] Co-simulation orchestrator requirements analysis
- [ ] API description V0.1
- [ ] POCs Orchestrator between two sims
- [ ] API description V0.2
- [ ] 3 simulator POC
- [ ] API description V1.0
- [ ] CI of 3 simulator POC

**Comment by lionelkusch** [comment]
Sandra (@sdiazpier) already start to think about the communication protocol for the orchestrator.
https://docs.google.com/spreadsheets/d/1yApDi33wwxcuMYCAhVOQoRILQSXdQE9kzX0gI1EsXkA/edit#gid=0

**Comment by lionelkusch** [comment]
In the proof of concept co-simulation TVB-Nest (https://github.com/multiscale-cosim/TVB-NEST), I separate the orchestrator to the simulators and translator modules.
This example can help you to define what is important for the API.

**Comment by dionperd** [comment]
The following comment relates to this issue:
https://github.com/multiscale-cosim/EBRAINS-cosim/issues/21#issuecomment-711877563

**Comment by dionperd** [comment]
Following up at this discussion, and as Lionel and I are trying to have our implementations of TVB - NEST co-simulation converge with the following two objectives:
-parallel co-simulation which is currently missing in my implementation,
-a more user-friendly -mid-term, temporary- interface that will allow us to do some science with tvb-multiscale in the weeks/months to come,

I came across this software Ray, which has the following nice features:
- it can parallelize for both PC and Cluster, e.g., see configuration for slurm: https://docs.ray.io/en/latest/cluster/slurm.html
- it has a very easy and intuitive user-interface, where remote class objects stand out, making it possible to e.g., run a notebook on a Head node and control interactively TVB and NEST running on other processes and resources (e.g., cluster nodes); I can have an example running in a few weeks I think,
- and I think it can work well with containers: https://docs.ray.io/en/ray-0.4.0/using-ray-and-docker-on-a-cluster.html

So, I would like to take a step forward from just using the subprocess Python module and use files in order to coordinate the Co-simulation, mainly because I want to support a similar user-experience people in my lab now have with sequential tvb-multiscale Co-simulation, on the scientific use-cases and projects that are currently running.

The use I envision is that the application starts from one Head node, perhaps running a Jupyter notebook, and two remote objects are formed, a TVB and a NEST orchestrator, which run on different processes and potentially different computational resources and can
- build the TVB and NEST network models,
- prepare the translators, including the MPI communication Lionel is currently using,
- perform several rounds of simulation - analysis - visualization,
- and finally terminate and clean up.

Initially, I envision this working on a single machine, but I hope that it could scale to a cluster, perhaps giving up some of this interactiveness.

I hope you find this a nice idea in the mid-term that could offer some more experience on the user interface(s) we need to implement for our project.

**Comment by dionperd** [comment]
See also this comment: https://github.com/multiscale-cosim/EBRAINS-cosim/issues/21#issuecomment-711913337

**Comment by maedoc** [comment]
I would suggest as a potential candidate for a single-source-of-truth key value store which could replace the endless config files.  Being non-MPI may be advantage as a sort of out-of-band channel if/when MPI issues arise.

**Comment by w-klijn** [comment]
We will have a first version in the MVP.
Pushed this to the next phase
