### ISSUE TITLE
Application Companion MVP

### ISSUE THREAD

**Issue by mfahdaz** [multiscale-cosim/EBRAINS-cosim#60]
Aspect       | Detail
--------------|--------------
Summary       | Application Companion MVP 
Task Area     |  Implementation
Assignee      |
Information   | 
Prerequisites | #51 #48 #49 #52 
Dependencies  |  

## Summary
Application Companion MVP provides the basic functionalities for managing and monitoring of the applications executing on the remote resources. It sits in between the orchestrator and the application process. The brief summary can  be found at #51. The detailed description and design can be found at [SRS and design document for Application Companion](https://drive.ebrains.eu/f/aeb9e06a64c746f49d43/).

MVP of multiscale co-simulation framework targets the single node deployment. Application Companion offers the following features for MVP:

- **Application Management**: It offers the application management by executing the following three basic steering commands: (INIT, START, END). It sets the affinity mask of the integrated application.
- **Application Monitoring**:  It offers the monitoring of resource utilization (such as the average CPU and memory consumption) by the integrated application. It also provides the underlying platform specific data, OS specific data and the process meta-data for the process executing the integrated application, 
- **Storage of the Monitored Data**: It offers the storing of monitored data to JSON files. The functionality for shipping of metrics for run-time profiling and Knowledge Graph will be extended in later iterations.
- **On-demand Monitoring**: It facilitates the launching of application without enabling the monitoring. However, it provides the functionality for managing the application.

## Tasks

- [x] POC
- [x] Application Manager: For executing the steering commands and to managing the application accordingly.
--  support for basic steering commands (INIT, START, END)
- [x] Affinity Manager: support for setting the affinity mask of the application companion and the main application
- [x] Signal Manager: support for capturing the forcefully quit/termination signals for a graceful termination
- [x] DB Manager: support for storing the monitoring data to JSON file
- [x] Resource usage monitoring: non-invasive monitoring of the resource usage by the integrated application
- [x] CPU utilization: support for average CPU utilization per second by the integrated application
- [x] Memory utilization: support for memory utilization (VSS, RSS, PSS, USS) by the integrated application
- [x] Process Meta-data: the meta-data of the process executing the integrated application. It includes PID, process name, exit code, etc.
- [x] Underlying platform: details on underlying 
-- hardware architecture details (architecture type, model name, vendor, maximum frequency, etc.)
-- OS specific details such as OS name, flavor, built, etc.
-- CPU: detailed information on the type of individual CPUs (processors) for all the CPUs present on the system.
- [x] Resource usage summary:  the summary of the resource usage statistics

## Acceptance criteria

Pass the integration tests with and without monitoring functionality.

**Comment by ringleschavez** [comment]
Aspect       | Detail
--------------|--------------
Summary       | Application Companion MVP 
Task Area     |  Implementation
Assignee      |
Information   | 
Prerequisites | 
Dependencies  | 

## Summary
Describes the Application Companion

## Tasks
- [ ] Definition of the Scope of the Application Companion
- [ ] Inputs/Outputs definition
- [ ] Protocol
- [ ] Parameters definition

## Requirements
Characterization of the different kinds of Application Companion used on Co-Simulation

## Acceptance criteria
Diagrams and its description about the general Application Companion

**Comment by mfahdaz** [comment]
Closed with [PR](https://github.com/multiscale-cosim/EBRAINS-RichEndpoint/pull/1) and [PR](https://github.com/multiscale-cosim/common-utils/pull/5).
