### ISSUE TITLE
1.1 Transformer MVP

### ISSUE THREAD

**Issue by mfahdaz** [multiscale-cosim/EBRAINS-cosim#61]
Aspect       | Detail
--------------|--------------
Summary       | 
Task Area     | 
Assignee      |
Information   | 
Prerequisites | 
Dependencies  | 

## Tasks

- [x] Update card, rename, change description
- [x] Compare implementation to design
    - [x] finish missing parts
    - [x] apply changes according to new design
- [x]  Test integration with other MVP components (Launcher, REP, ...)

_(old tasks updated)_

**Comment by sontheimer** [comment]
Next steps:
- [ ] Update name and description
- [ ] check new tasks
- [ ] add proper dependencies and links to other cards

**Comment by sontheimer** [comment]
Transformer renamed to InterscaleHUB, details moved to new card.
