### ISSUE TITLE
2.x Repository Layout

### ISSUE THREAD

**Issue by w-klijn** [multiscale-cosim/EBRAINS-cosim#64]
Aspect       | Detail
--------------|--------------
Summary       | Code reviews are important for automated deployment. We need to have a well formalize repo organization
Task Area     |  Installation
Assignee      | Wouter
Information   | 
Prerequisites | 
Dependencies  | #36 

## Summary
CO simulation use-cases are a combination of models, code and configuration that together implement the science case. The aim is to enable automated deployment on HPC. For this we can not have random code deployed on the system. All code parts need to go to a review process. In addition to this we have version dependencies on the different simulators.

To streamline this process for the first use-cases we will create a repository with use-case specific code. allowing us to assign specific reviewers / responsible persons for updates on the code. To prevent a wild growth in how these repos are layed out. We should create a template / baseline repository that should guide the creation of these repositories

## Tasks
- [x] Formalize requirements
- [x] From scratch create a repo with sub projects / etc.
- [x] test git submodule behaviour (in template) when release of a new version
- [x] test using the template
- [x] cleanup / complete the diagrams
- [x] documentation of the process

## Acceptance criteria

- [x] created template repo with submodules
- [x] POSTPONED: instantiated repo for Lionels usecase from a copy of the template

**Comment by w-klijn** [comment]
Appears to have overlap with #36

**Comment by w-klijn** [comment]
Must be done for the first release.
We need a process for validating code, because we will be doing automated launches.

**Comment by w-klijn** [comment]
20 hours

**Comment by w-klijn** [comment]
For next team meeting have a visualization of the different options so we can discuss and plan implementation

**Comment by sontheimer** [comment]
[Visualization](https://drive.google.com/file/d/19qnyPiOh2Ve2ALk3vjVHgONrhNv89NE2/view) of the current Layout.

Base for our next discussion round.

**Comment by sontheimer** [comment]
started first tests for a template repository

**Comment by sontheimer** [comment]
Created first version of the template.
