### ISSUE TITLE
HPC communication stack

### ISSUE THREAD

**Issue by w-klijn** [multiscale-cosim/EBRAINS-cosim#7]
Aspect       | Detail
--------------|--------------
Summary       | The communication stack between the different multi-scale components
Task Area     | Feature
Assignee      | Lena Oden
Information   | 
Prerequisites | 
Dependencies  | 

## Summary
In the currently available POC different communication methods are used. ZeroMQ, MPI, TCP-IP. This complicates integration into the different components of co-simulation. The HPC communication stack will provide a single API to abstracts away from the different communication methods. And provides a single data description.
Complicating this effort is the diverse nature of the data exchanged and the requirements for fast exchange for the tightly couple neuro simulators. Visualization/analysis typically is not tightly couple but is more diverse in nature and can vary in size greatly on runtime parameter selection.

## Tasks
- [ ] Requirements analysis viz/analysis
- [ ] Requirements analysis simulators
- [ ] API description V0.1
- [ ] POCs Orchestrator between two sims

**Comment by w-klijn** [comment]
Continued in #48
