### ISSUE TITLE
MPI Client/Server getting information

### ISSUE THREAD

**Issue by ringleschavez** [multiscale-cosim/EBRAINS-cosim#73]
Aspect       | Detail
--------------|--------------
Summary       | Grabbing information how to use MPI client/server implementation mechanisms
Task Area     | Getting Knowledge
Assignee      |
Information   | 
Prerequisites | 
Dependencies  | 

## Summary
The MPI client/server approach imply certain considerations in order to implement
servers, since when multiple MPI processes are started as server, the whole system
could be frozen.

## Tasks
- [x] Check Information about MPI client/server usage
- [x] Develop a proof of concept code just to test the approach
- [x] Fix the Integration test committed by means of https://github.com/multiscale-cosim/TVB-NEST/pull/15
