### ISSUE TITLE
Testing Co-Simulator TVB-NEST/launcher on FZJ/JSC/SCs infrastructure 

### ISSUE THREAD

**Issue by ringleschavez** [multiscale-cosim/EBRAINS-cosim#74]
Aspect       | Detail
--------------|--------------
Summary       | Deploy the current version of the Co-Simulator 
Task Area     | 
Assignee      |
Information   | 
Prerequisites | 
Dependencies  | 

## Tasks
- [ ] Setting-Up user accounts on SCs
- [ ] Getting knowledge how to deploy jobs on SCs
- [ ] Getting knowledge about brain simulators on SCs (how they are deployed/called)
- [ ] Prepare SCs environment to deploy/execute the Integration Tests

**Comment by ringleschavez** [comment]
[C.E.C.I.'s Slurm F.A.Q.](https://support.ceci-hpc.be/doc/_contents/SubmittingJobs/SlurmFAQ.html)
taken from 
[HPC cluster: select the number of CPUs and threads in SLURM sbatch](https://stackoverflow.com/questions/51139711/hpc-cluster-select-the-number-of-cpus-and-threads-in-slurm-sbatch)
- Using MPI and do not care about where those cores are distributed: `--ntasks=16`
- Launching 16 independent processes (no communication): `--ntasks=16`
- Spreading those cores across distinct nodes: `--ntasks=16 and --ntasks-per-node=1` or `--ntasks=16 and --nodes=16`
- Spreading those cores across distinct nodes and no interference from other jobs: `--ntasks=16 --nodes=16 --exclusive`
- Spreading 16 processes across 8 nodes to have two processes per node: `--ntasks=16 --ntasks-per-node=2`
- Setting 16 processes up to stay on the same node: `--ntasks=16 --ntasks-per-node=16`
- Setting one process up able to use 16 cores for multithreading: `--ntasks=1 --cpus-per-task=16`
- Setting 4 processes that can use 4 cores each for multithreading: `--ntasks=4 --cpus-per-task=4`

**Comment by ringleschavez** [comment]
Having executed the ${MULTISCALETVBNEST}/launcher/tests/plans/simple_plan_on_cluster.xml
on JUWELS, it has been noticed that some ERROR messages were thrown. NEVERTHELESS,
slurm tool commands send some informative message to the stderr, i.e. the Co-Simulator
reports such message as ERROR because they were gotten from the stderr buffer.

`
2021-06-21 14:20:54,834 - INFO - common.cosimulator - [Spawner-2:20460] - action_004: PPID=24823,PID=24829,MPI.COMM_WORLD.size=2,MPI.COMM_WORLD.rank=0,MPI.processor_name=jwc00n014.juwels
2021-06-21 14:20:54,834 - ERROR - common.cosimulator - [Spawner-2:20460] - action_004: srun: job 3884042 queued and waiting for resources
2021-06-21 14:20:54,834 - INFO - common.cosimulator - [Spawner-2:20460] - action_004: PPID=24824,PID=24830,MPI.COMM_WORLD.size=2,MPI.COMM_WORLD.rank=1,MPI.processor_name=jwc00n014.juwels
2021-06-21 14:20:54,834 - ERROR - common.cosimulator - [Spawner-2:20460] - action_004: srun: job 3884042 has been allocated resources
2021-06-21 14:20:55,037 - INFO - common.cosimulator - [Spawner-1:20459] - action_006: PPID=16355,PID=16360,MPI.COMM_WORLD.size=2,MPI.COMM_WORLD.rank=0,MPI.processor_name=jwc00n004.juwels
2021-06-21 14:20:55,037 - ERROR - common.cosimulator - [Spawner-1:20459] - action_006: srun: job 3884043 queued and waiting for resources
2021-06-21 14:20:55,037 - INFO - common.cosimulator - [Spawner-1:20459] - action_006: PPID=16356,PID=16362,MPI.COMM_WORLD.size=2,MPI.COMM_WORLD.rank=1,MPI.processor_name=jwc00n004.juwels
2021-06-21 14:20:55,037 - ERROR - common.cosimulator - [Spawner-1:20459] - action_006: srun: job 3884043 has been allocated resources
2021-06-21 14:20:55,039 - INFO - common.cosimulator - [Spawner-2:20460] - action_004: PPID=24824, PID=24830, Cosimulation_outputs/ingleschavez1_outputs_2021-06-21_142021/results/simple_test/24830.output has been generated
2021-06-21 14:20:55,039 - INFO - common.cosimulator - [Spawner-2:20460] - action_004: PPID=24823, PID=24829, Cosimulation_outputs/ingleschavez1_outputs_2021-06-21_142021/results/simple_test/24829.output has been generated
2021-06-21 14:20:55,039 - INFO - common.cosimulator - [Spawner-2:20460] - Action <action_004> finished properly.
2021-06-21 14:20:55,039 - INFO - common.cosimulator - [Spawner-2:20460] - PPID=20458,PID=20460,Spawner-2: the <action_004> action has finished
`

**Comment by ringleschavez** [comment]
The issue #112 has been created based on the already dropped task:
- LOCAL: Prepare XML configuration files to run the Zerlaut's brain simulation by means of the workflow implemented on - [ ] https://github.com/multiscale-cosim/TVB-NEST/blob/master/tests/test_co-sim.sh
