### ISSUE TITLE
Getting the hang of MPI's Shared-Memory Approach

### ISSUE THREAD

**Issue by ringleschavez** [multiscale-cosim/EBRAINS-cosim#75]
Aspect       | Detail
--------------|--------------
Summary       | MPI's Shared-Memory getting knowledge
Task Area     | 
Assignee      |
Information   | 
Prerequisites | 
Dependencies  | 

## Summary
The outcome of this issue will be the definition of the proper mechanism to be used as communication
layer among the Co-Simulation actors (i.e. simulators, transformers, visualizer)

## Tasks
- [ ] Getting the hang of Shared-Memory usage by means of MPI
- [ ] Develop a ring-buffer by using a MPI's shared-memory window
- [ ] Develop a proof-of-concept consumer/producer ping-pong application
- [ ] Testing on multiple-nodes cluster to confirm the scope of MPI's memory sharing
- [ ] Develop a proof-of-concept consumerS/producer application including synchronization mechanism
- [ ] Develop a proof-of-concept consumerS/producerS application including a shared 3D data-structure
- [ ] Confirm the synchronization primitives provided by MPI implementations and its usage on MPI Shared-Memory

**Comment by ringleschavez** [comment]
This issue could be dropped there won't be any other action related to getting information about MPI's shared memory usage for Co-Simulation.
