### ISSUE TITLE
Working through OpenMPI Socket-Style Communication on CSCS's Piz Daint

### ISSUE THREAD

**Issue by ringleschavez** [multiscale-cosim/EBRAINS-cosim#76]
Aspect       | Detail
--------------|--------------
Summary       | Troubleshooting of TVB-NEST use-case on CSCS infrastructure 
Task Area     | Deployment Troubleshooting
Assignee      |
Information   | https://github.com/multiscale-cosim/TVB-NEST
Prerequisites | 
Dependencies  | 

## Summary
Making work the [TVB-NEST](https://github.com/multiscale-cosim/TVB-NEST) use-case 
on the CSCS infraestructure environment.

## Contraints:
- No Containers
- OpenMPI 4.1.1

## Tasks
- [x] Getting access to the CSCS's infrastructure
- [x] Compiling OpenMPI 4.1.1
- [x] Client/Server test based on OpenMPI 4.1.1
- [x] Testing Client/Server approach using compiled OpenMPI 4.1.1 on compute-node (single-node)
- [x] Testing Client/Server approach using compiled OpenMPI 4.1.1 on compute-node (multiple-node)

## Acceptance criteria
Making work client/server approach (MPI socket-style communication) on Piz Daint by using multiple compute-nodes

**Comment by ringleschavez** [comment]
### Compiling OpenMPI 4.1.1 on CSCS's Piz Daint system
 ```
cd $SCRATCH
 tar xzf openmpi-4.1.1.tar.gz
 cd openmpi-4.1.1/
./configure --prefix=${SCRATCH}/usr/local
mkdir -p ${SCRATCH}/usr/local
make -j 32
make install
```

**Comment by ringleschavez** [comment]
### Source code for testing
[haskell-mpi/test/examples/clientserver/](https://github.com/bjpop/haskell-mpi/tree/master/test/examples/clientserver

**Comment by ringleschavez** [comment]
### Test on CSCS's Piz Daint login node
#### Terminal 1 (OpenMPI orte-server)
```
module load daint-mc
cd ${SCRATCH}/testing_code/
export PATH=${SCRATCH}/usr/local/bin:${PATH}
export LD_LIBRARY_PATH=${SCRATCH}/usr/local/bin:${LD_LIBRARY_PATH}
ompi-server --debug --no-daemonize --report-uri RTE.data.server
```

#### Terminal 2 (Server)
```
module load daint-mc
cd ${SCRATCH}/testing_code/
export PATH=${SCRATCH}/usr/local/bin:${PATH}
export LD_LIBRARY_PATH=${SCRATCH}/usr/local/bin:${LD_LIBRARY_PATH}
mpiexec --ompi-server file:RTE.data.server -np 1 ./server
```

#### Terminal 3 (Client)
```
module load daint-mc
cd ${SCRATCH}/testing_code/
export PATH=${SCRATCH}/usr/local/bin:${PATH}
export LD_LIBRARY_PATH=${SCRATCH}/usr/local/bin:${LD_LIBRARY_PATH}
mpiexec --ompi-server file:RTE.data.server -np 1 ./client <ThePortCreatedByTheServer>
```

**Comment by ringleschavez** [comment]
It is possible to use the _Socket-Style Communication_ on single-node, since the server and client binaries are launch by means of `slurm + mpirun,` notwithstanding, on multiple-nodes, when `mpirun` is used, multiple instances of the mentioned binaries are launched which is not the expected operation on run-time.

After testing several alternatives of compiling **OpenMPI 4.1.1** on Piz Daint, the conclusion is `SLURM` tools running on Piz Daint should provide the proper `PMI` or `PMIx` interface in order to use the _Socket-Style Communication_ approach implemented on  **OpenMPI 4.1.1.**

**Comment by ringleschavez** [comment]
[OpenMPI on CSCS Piz Daint.pdf](https://github.com/multiscale-cosim/EBRAINS-cosim/files/7463999/OpenMPI.on.CSCS.Piz.Daint.pdf)
is the first draft showing the outcomes of the tested compilation process.
