### ISSUE TITLE
Basic Monitoring

### ISSUE THREAD

**Issue by w-klijn** [multiscale-cosim/EBRAINS-cosim#8]
Aspect       | Detail
--------------|--------------
Summary       | Basic monitoring of the deployed application using ELK
Task Area     | Feature
Assignee      | Kim Sontheimer
Information   | k.sontheimer@fz-juelich.de 
Prerequisites | 
Dependencies  | 

## Summary
Manually checking the application state of multiple applications is unfeasible for multi-application workflows. To this end a basic ELK stack will be deployed to enable basic monitoring. This will include log-file parsing of the different applications and co-simulation framework components.

## Tasks
- [ ] ELK installation (see #26 )
- [ ] Basic monitoring applications
- [ ] Basic monitoring framework
- [ ] Basic monitoring hardware systems
- [ ] Dashboard for basic deployment insight

## Requirements
- 3-5 VMs (Elasticsearch, Logstash, Kibana) 
    - 8 CPUs
    - 20 GB RAM
    - 430GB HDD
    - floating IPs for access from outside 

## Acceptance criteria
Installed and online ELK stack and basic monitoring of a running application.

**Comment by w-klijn** [comment]
Work has been hand over to TC.

Closed for Cosim at this stage
