### ISSUE TITLE
Working through TVB-NEST Co-Simulation Use-Case on CSCS 

### ISSUE THREAD

**Issue by ringleschavez** [multiscale-cosim/EBRAINS-cosim#81]
Aspect       | Detail
--------------|--------------
Summary       | Troubleshooting of TVB-NEST use-case on CSCS infrastructure 
Task Area     | Deployment Troubleshooting
Assignee      |
Information   | https://github.com/multiscale-cosim/TVB-NEST
Prerequisites | 
Dependencies  | 

## Summary
Making work the [TVB-NEST](https://github.com/multiscale-cosim/TVB-NEST) use-case 
on the CSCS infraestructure environment.

## Contraints:
- No Containers
- OpenMPI 4.1.1

## Tasks
- [ ] Setting-Up the environment to run the TVB-NEST use-case
- [ ] Deploy latest version of the TVB-NEST repository into the CSCS's infraestructure
- [ ] Troubleshooting starting selected use-case
- [ ] Troubleshooting of run-time issues
- [ ] Tuning run-time environment (if it is feasible) 
- [ ] Tuning code (if it is a must or feasible) 
- [ ] Performance improvement (getting bottlenecks and its possible fix (it it is feasible))

NOTE: feasibility is in connection with technology restrictions/constraint and mostly with developing time.

## Requirements

#76 

## Acceptance criteria
Making work the selected use-case simplemented on [TVB-NEST](https://github.com/multiscale-cosim/TVB-NEST)
