### ISSUE TITLE
2.3 Working through OpenMPI Socket-Style Communication on JSC's JUSUF

### ISSUE THREAD

**Issue by ringleschavez** [multiscale-cosim/EBRAINS-cosim#82]
Aspect       | Detail
--------------|--------------
Summary       | Troubleshooting of TVB-NEST use-case on CSCS infrastructure 
Task Area     | Deployment Troubleshooting
Assignee      |
Information   | https://github.com/multiscale-cosim/TVB-NEST
Prerequisites | 
Dependencies  | 

## Summary
Making work the [TVB-NEST](https://github.com/multiscale-cosim/TVB-NEST) use-case 
on the CSCS infraestructure environment.

## Contraints:
- No Containers
- OpenMPI 4.1.1

## Tasks
- [x] Getting access to the FZJ/JSC/JUSUF infrastructure
- [x] Compiling OpenMPI 4.1.1
- [x] Client/Server test based on the already installed OpenMPI 4.1.1
- [x] Testing Client/Server approach using compiled OpenMPI 4.1.1 on compute-node (single-node)
- [x] Testing Client/Server approach using compiled OpenMPI 4.1.1 on compute-node (multiple-node)

## Acceptance criteria
Making work client/server approach (MPI socket-style communication) on Piz Daint by using multiple compute-nodes

**Comment by ringleschavez** [comment]
Having checked the MPI frameworks available on JUSUF, there were found the followings:

### OpenMPI
```
@jsfl01 ~]$ module spider OpenMPI

----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  OpenMPI:
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    Description:
      The Open MPI Project is an open source MPI-3 implementation.

     Versions:
        OpenMPI/4.1.0rc1
        OpenMPI/4.1.1
```

### ParaStationMPI
```
@jsfl01 ~]$ module spider ParaStationMPI

----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  ParaStationMPI:
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    Description:
      ParaStation MPI is an open source high-performance MPI 3.0 implementation, based on MPICH v3. It provides extra low level communication libraries and integration with various batch systems for tighter
      process control. 

     Versions:
        ParaStationMPI/5.4.7-1-mt
        ParaStationMPI/5.4.7-1
        ParaStationMPI/5.4.8-1
        ParaStationMPI/5.4.9-1-mt
        ParaStationMPI/5.4.9-1
        ParaStationMPI/5.4.10-1-mt
        ParaStationMPI/5.4.10-1
```

**Comment by ringleschavez** [comment]
As it could be seen on the previous comment, OpenMPI 4.1.1 is already installed on JUSUF, meaning that only remains the Socket-Style Communication approach by using such framework.

Additionally, just to confirm which version support the mentioned communication approach, the client/server source code will be compiled using the other MPI frameworks.

**Comment by ringleschavez** [comment]
In order to use OpenMPI 4.1.1 on JUSUF, other modules must be loaded before hand, i.e.:
```jsfl02 ~]$ module spider OpenMPI/4.1.1

----------------------------------------------------------------------------------------------------
  OpenMPI: OpenMPI/4.1.1
-----------------------------------------------------------------------------------------------------
    Description:
      The Open MPI Project is an open source MPI-3 implementation.

    Properties:
      built for GPU

    You will need to load all module(s) on any one of the lines below before the "OpenMPI/4.1.1" module is available to load.

      Stages/2020  GCC/10.3.0
      Stages/2020  Intel/2021.2.0-GCC-10.3.0
      Stages/2020  NVHPC/21.5-GCC-10.3.0
      Stages/2020  NVHPC/21.9-GCC-10.3.0
      Stages/2022  GCC/11.2.0

```

**Comment by ringleschavez** [comment]
Another issue: [7094](https://github.com/open-mpi/ompi/issues/7094)

**Comment by ringleschavez** [comment]
There was a confirmation from Sandra that multi-node does not work properly, more research and support might be needed.
