### ISSUE TITLE
Simlab Cosim presentation / workshop

### ISSUE THREAD

**Issue by w-klijn** [multiscale-cosim/EBRAINS-cosim#85]
Aspect       | Detail
--------------|--------------
Summary       | Outreach
Task Area     | User
Assignee      | Wouter Klijn
Information   | Beginning January there will be a simlab workshop for Bernstein, Cosim is invited to give a presentation

## Summary
It would be good to use this as a basis for creating a standardized talk for introducing Cosim to users. Not a science talk but towards a hand-on.

## Tasks
- [ ] Decide who presents
- [ ] Review slide deck
- [ ] Review course material by non cosim member
