### ISSUE TITLE
Multi-scale translator

### ISSUE THREAD

**Issue by w-klijn** [multiscale-cosim/EBRAINS-cosim#9]
Aspect       | Detail
--------------|--------------
Summary       | Translator between spikes and x, enabling coupling between NEST/Arbor and TVB using Elephant
Task Area     | Functionality
Assignee      | Kim, Lionel
Information   | 
Prerequisites | #10 
Dependencies  | 

## Summary
NEST/Arbor and TVB speak different languages: NEST and Arbor typically exchange spikes where TVB is 'rate' based. The information stream needs to be translate at runtime. To allow reuse of the existing spiketrain analysis functionality Elephant should be used to do this translation.

Lionel has a working POC coupling TVB and NEST. And Kim has a POC allowing Many to one MPI distribution and deployment. The lessons learned from these two 

## Tasks
- [x] Running deployment of Lionel existing POC on Deep-est (see #26)
- [x] Running deployment of Kim's existing POC on Deep-est (see #26)
    - [ ] Code cleanup and refactoring, initial push here.
- [x] Requirements analysis (done in diagrams.net) 
- [ ] use existing refactoring (fzj gitlab)
    - [x] Add thread handling
    - [x] Add correct break/cancel functionality

**Comment by sontheimer** [comment]
Test comment

**Comment by w-klijn** [comment]
A first design document can be found here:
https://docs.google.com/document/d/13hIfdwWZvI-7cOSrwVmDltSPP2-qtQ9mlU4uj9CcV5I/edit#heading=h.26in1rg

**Comment by sontheimer** [comment]
Nest-Elephant (in transit) coupling deployed and tested in alpha version on deepest (July 13th, 2020).
